server:
  port: ${SERVER_PORT:999}
owners:
  namesOwnerTelegramBot:
    - ilai_s
  pass: ${WEB_PASS:admin}
file:
  pathDownload: ${PATH_DOWNLOAD:/}
  size: ${SIZE_FILE:5000}
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
ssh-server:
  ip: 111.111.11.11
  port: ${SSH_PORT:22}
  user: ${SSH_USER}
  pathToPrivateKey: ${SSH_PRIVATE_KEY_PATH:/home/id_rsa}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update
